name: pre-commit
on:
  pull_request:
  workflow_dispatch:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11.2'

      - uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Spotless
        run: gradle spotlessCheck

      - uses: pre-commit/action@v3.0.0
        with:
          extra_args: "--all-files"

      - uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.5
